### ISSUE TITLE
Need unsubscribeEvent

### ISSUE THREAD

**Issue by drewbaker** [nghiepit/ui-event-performance#2]
Would be nice if you had a way to unsubscribe from your event `subscribeEvent`.

**Comment by nghiepdev** [comment]
Maybe, we can unsubscribe. But, before unsubscribe, you must remove EventListener.

Like that:
```js
const unsubscribeEvent = subscribeEvent('resize', 'optimizedResize');
window.addEventListener('optimizedResize', handler);

// Remove Event Listener
window.removeEventListener("optimizedResize", handler);

// Unsubscribe Event
unsubscribeEvent();
```

**Comment by drewbaker** [comment]
> Maybe, we can unsubscribe.

Do you mean that this works currently, or is this the idea you have to implement?

**Comment by nghiepdev** [comment]
@drewbaker 
I've just published. Now you can unsubscribe event.
